// frontend/frontoffice/src/components/Navbar/index.jsx
import React from "react";
import Container from "react-bootstrap/Container";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import { isAuthenticated, getUsername } from "modules/auth";
import UserAPI from "modules/api/user";

export default class NavbarComponent extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            name: null,
            surname: null,
            username: null,
            is_auth: false
        };
    }

    async componentDidMount() {
        this.setState({ is_auth: await isAuthenticated() });

        if (await isAuthenticated()) {
            const user = await UserAPI.getProfile(await getUsername());

            this.setState({
                name: user.name,
                surname: user.surname,
                username: user.username,
                picture: user.picture ? `${process.env.REACT_APP_DOMAIN}${user.picture}` : `${process.env.REACT_APP_DOMAIN}/profiles/images/default.png`
            });
        }
    }
    
    render() {
        return (<>
            <nav>
                <Navbar expand="lg" style={{ backgroundColor: "#ffa545" }}>
                    <Container fluid>
                        <Navbar.Brand href="/">
                            <div className="d-flex justify-content-center align-items-center">
                                <img src={`${process.env.REACT_APP_DOMAIN}/logos/logo.png`} alt="" style={{height: "2rem"}} />
                            </div>
                        </Navbar.Brand>
                        <Navbar.Toggle aria-controls="basic-navbar-nav" />
                        <Navbar.Collapse id="basic-navbar-nav">
                            <Nav className="me-auto">
                                <Nav.Link className="text-dark" href="/">Home</Nav.Link>
                                <Nav.Link className="text-dark" href="/services-list">Servizi</Nav.Link>
                                <Nav.Link className="text-dark" href="/fo/shop">Shop</Nav.Link>
                                <Nav.Link className="text-dark" href="/hubs-list">Sedi</Nav.Link>
                                <Nav.Link className="text-dark" href="/fo/forum">Forum</Nav.Link>
                                <Nav.Link className="text-dark" href="/play">Giochi</Nav.Link>
                                {
                                    !this.state.is_auth &&
                                    <Nav.Link className="text-dark" href="/fo/my-animals">Presentati</Nav.Link>
                                }
                                { this.state.is_auth && <Nav.Link className="text-dark" href="/fo/vip">VIP</Nav.Link> }
                            </Nav>

                            <div className="justify-content-end">
                            {
                                this.state.username &&
                                <div className="dropdown d-inline-block">
                                    <button className="btn dropdown-toggle text-dark p-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <div className="d-inline-block">
                                            <div className="d-flex align-items-center">
                                                <span className="align-top me-2">{ this.state.name } { this.state.surname }</span>
                                                <div className="d-flex align-items-center justify-content-center border border-dark rounded-circle overflow-hidden" style={{ height: "2.2rem", width: "2.2rem" }}>
                                                    <div className="d-flex justify-content-center align-items-center">
                                                        <img src={`${this.state.picture}`} alt="Immagine di profilo" style={{ maxHeight: "2.2rem" }} />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </button>
                                    <ul className="dropdown-menu dropdown-menu-end">
                                        <li><span className="dropdown-item-text fw-bold" aria-label="Username corrente">{ this.state.username }</span></li>
                                        <div className="dropdown-divider"></div>
                                        <li><a className="dropdown-item" href={`/fo/profile?username=${this.state.username}`}>Profilo</a></li>
                                        <li><a className="dropdown-item" href="/fo/my-animals">I miei animali</a></li>
                                        <li><a className="dropdown-item" href="/fo/appointments">I miei appuntamenti</a></li>
                                        <li><a className="dropdown-item" href="/fo/shop/orders">I miei ordini</a></li>
                                        <li><a className="dropdown-item" href="/fo/settings">Impostazioni</a></li>
                                        <li><a className="dropdown-item" href="/fo/logout">Logout</a></li>
                                    </ul>
                                </div>
                            }
                            {
                                !this.state.username &&
                                <div>
                                    <a className="btn btn-primary text-decoration-none mx-1" href="/fo/signup">Registrati</a>
                                    <a className="btn btn-primary text-decoration-none mx-1" href={`/fo/login?return=${window.location.href}`}>Login</a>
                                </div>
                            }
                            </div>
                        </Navbar.Collapse>
                    </Container>
                </Navbar>
            </nav>
        </>);
    }
}

// frontend/game/src/components/Navbar/Navbar.vue
<template>
    <nav class="navbar navbar-expand-lg mb-3" style="background-color: #9ed700;">
        <div class="container-fluid">
            <router-link to="/" class="navbar-brand">
                <div class="d-flex align-items-center justify-content-center">
                    <img :src="`${DOMAIN}/logos/logo.png`" alt="" style="max-height: 2rem; max-width: 2rem;">
                </div>
            </router-link>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav me-auto">
                    <router-link to="/" class="nav-link active">Home</router-link>
                    <router-link to="/services-list" class="nav-link active">Servizi</router-link>
                    <a :href="`${DOMAIN}/fo/shop`" class="nav-link active">Shop</a>
                    <router-link to="/hubs-list" class="nav-link active">Sedi</router-link>
                    <a :href="`${DOMAIN}/fo/forum`" class="nav-link active">Forum</a>
                    <router-link to="/play" class="nav-link active">Giochi</router-link>
                    <a v-if="!is_auth" :href="`${DOMAIN}/fo/my-animals`" class="nav-link active">Presentati</a>
                    <a v-if="is_auth" :href="`${DOMAIN}/fo/vip`" class="nav-link active">VIP</a>
                </div>

                <div class="justify-content-end">
                    <div v-if="username" class="dropdown d-inline-block">
                        <button class="btn dropdown-toggle text-dark p-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="d-inline-block">
                                <div class="d-flex align-items-center">
                                    <span class="align-top me-2">{{ name }} {{ surname }}</span>
                                    <div class="d-flex align-items-center justify-content-center border border-dark rounded-circle overflow-hidden" style="height: 2.2rem; width: 2.2rem">
                                        <div class="d-flex justify-content-center align-items-center">
                                            <img :src="picture" alt="Immagine di profilo" style="max-height: 2.2rem" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><span class="dropdown-item-text fw-bold" aria-label="Username corrente">{{ username }}</span></li>
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" :href="`/fo/profile?username=${username}`">Profilo</a></li>
                            <li><a class="dropdown-item" href="/fo/my-animals">I miei animali</a></li>
                            <li><a class="dropdown-item" href="/fo/appointments">I miei appuntamenti</a></li>
                            <li><a class="dropdown-item" href="/fo/shop/orders">I miei ordini</a></li>
                            <li><a class="dropdown-item" href="/fo/settings">Impostazioni</a></li>
                            <li><a class="dropdown-item" href="/fo/logout">Logout</a></li>
                        </ul>
                    </div>

                    <div v-if="!username">
                        <a class="btn btn-primary text-decoration-none mx-1" :href="`${DOMAIN}/fo/signup`">Registrati</a>
                        <a class="btn btn-primary text-decoration-none mx-1" :href="`${DOMAIN}/fo/login?return=${LOCATION_HREF}`">Login</a>
                    </div>
                </div>

            </div>
        </div>
    </nav>
</template>

<script>
    import "bootstrap"; 
    import { isAuthenticated, getUsername } from "modules/auth";
    import UserAPI from "modules/api/user";

    export default {
        name: "navbar",
        
        data() {
            return {
                is_auth: false,
                username: null,
                name: null,
                surname: null,
                picture: null
            }
        },
        
        computed: {
            DOMAIN() { return process.env.VUE_APP_DOMAIN; },
            LOCATION_HREF() { return window.location.href; }
        },

        async mounted() {
            this.is_auth = await isAuthenticated();

            if (this.is_auth) {
                const user = await UserAPI.getProfile(await getUsername());

                this.name = user.name,
                this.surname = user.surname,
                this.username = user.username,
                this.picture = user.picture ? `${process.env.VUE_APP_DOMAIN}${user.picture}` : `${process.env.VUE_APP_DOMAIN}/profiles/images/default.png`
            }
        },
    }
</script>

<style lang="scss">
    @import "../../scss/bootstrap.scss";
</style>
